### ISSUE TITLE
err when pip install hydra-core==0.11

### ISSUE THREAD

**Issue by dbdxnuliba** [gtrll/gpmp2#64]
I has sucess install gpmp2 by following  https://github.com/gtrll/gpmp2/tree/main/projects/jist
but when I pip install hydra-core==0.11 , some error ocurrs:

(gpmp2) dell@dell:~/ref/gpmp2/gpmp2_python$ pip install hydra-core==0.11
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: http://pypi.douban.com/simple
Collecting hydra-core==0.11
  Downloading http://pypi.doubanio.com/packages/3e/88/00b69538123d239de1f30be7ee069975687fbf2bcf0e59c6e5061410428f/hydra-core-0.11.0.tar.gz (42 kB)
     |################################| 42 kB 81 kB/s 
Collecting omegaconf>=1.4.0
  Downloading http://pypi.doubanio.com/packages/a2/49/91b8c32d0d047c65c8aa2d4cf95c901428e4eb8657681034bbe12b22c0fd/omegaconf-1.4.1.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dell/miniconda3/envs/gpmp2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1OYMzg/omegaconf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1OYMzg/omegaconf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t3uBKN
         cwd: /tmp/pip-install-1OYMzg/omegaconf/
    Complete output (25 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    WARNING: The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.douban.com'.
    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1OYMzg/omegaconf/setup.py", line 72, in <module>
        "lint": ["black", "flake8"],
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/dell/miniconda3/envs/gpmp2/lib/python2.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/dell/miniconda3/envs/gpmp2/bin/python2.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpGmev4L', '--quiet', 'pytest-runner']' returned non-zero exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by dbdxnuliba** [comment]
I have solved it by pip install pytest-runner
